import { useAuthentication } from "./hooks";

import type { NextPage } from "next";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Sidebar } from "./components/sidebar";

const UserIcon: string =
    "https://cdn.wikirby.com/8/81/Kirby_JP_Twitter_Old_Icon.jpg";

const Home: NextPage = () => {
    const { login, logout, idToken } = useAuthentication();

    return (
        <div className={styles.container}>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <button onClick={login}>login</button>
            <button onClick={logout}>logout</button>
            <body style={{ margin: 0, minHeight: "100vh" }}>
                <header style={{ backgroundColor: "red", zIndex: 900 }}>
                    <h1>a</h1>
                </header>
                <Sidebar
                    userDatas={[
                        { Name: "User", Icon: "null" },
                        { Name: "Image", Icon: UserIcon },
                    ]}
                />
            </body>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};
