import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Sidebar } from "./components/sidebar";

const UserIcon: string = "https://cdn.wikirby.com/8/81/Kirby_JP_Twitter_Old_Icon.jpg";



const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body style={{margin: 0, minHeight: "100vh"}}>
            <header style={{backgroundColor: "red" , zIndex: 900}}><h1>a</h1></header>
            <Sidebar userDatas={[{Name: "User", Icon: "null"}, {Name: "Image", Icon: UserIcon}]}/>
            </body>
        </div>
    );
};

export default Home;
